// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logger/options.proto

// Protobuf Java Version: 3.25.5
package logger;

public final class Options {
  private Options() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(logger.Options.redactFormat);
    registry.add(logger.Options.name);
    registry.add(logger.Options.sensitivity);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code logger.Sensitivity}
   */
  public enum Sensitivity
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Unannotated default — safe to log.
     * Identifiers, IDs, timestamps, enums, status fields.
     * </pre>
     *
     * <code>SENSITIVITY_UNSPECIFIED = 0;</code>
     */
    SENSITIVITY_UNSPECIFIED(0),
    /**
     * <pre>
     * User-identifying or user-controlled data: display names, phone numbers,
     * metadata, attributes, custom headers, auth usernames, semi-public account
     * identifiers (AWS role ARNs, Azure account names).
     * Redacted by logger.Proto(); exposed by logger.UnredactedProto() for
     * operator-facing observability events.
     * </pre>
     *
     * <code>SENSITIVITY_PII = 1;</code>
     */
    SENSITIVITY_PII(1),
    /**
     * <pre>
     * Credentials and authentication material: passwords, access keys, session
     * tokens, signing keys, API keys, ICE credentials.
     * ALWAYS redacted, including by logger.UnredactedProto().
     * </pre>
     *
     * <code>SENSITIVITY_SECRET = 2;</code>
     */
    SENSITIVITY_SECRET(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Unannotated default — safe to log.
     * Identifiers, IDs, timestamps, enums, status fields.
     * </pre>
     *
     * <code>SENSITIVITY_UNSPECIFIED = 0;</code>
     */
    public static final int SENSITIVITY_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * User-identifying or user-controlled data: display names, phone numbers,
     * metadata, attributes, custom headers, auth usernames, semi-public account
     * identifiers (AWS role ARNs, Azure account names).
     * Redacted by logger.Proto(); exposed by logger.UnredactedProto() for
     * operator-facing observability events.
     * </pre>
     *
     * <code>SENSITIVITY_PII = 1;</code>
     */
    public static final int SENSITIVITY_PII_VALUE = 1;
    /**
     * <pre>
     * Credentials and authentication material: passwords, access keys, session
     * tokens, signing keys, API keys, ICE credentials.
     * ALWAYS redacted, including by logger.UnredactedProto().
     * </pre>
     *
     * <code>SENSITIVITY_SECRET = 2;</code>
     */
    public static final int SENSITIVITY_SECRET_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Sensitivity valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Sensitivity forNumber(int value) {
      switch (value) {
        case 0: return SENSITIVITY_UNSPECIFIED;
        case 1: return SENSITIVITY_PII;
        case 2: return SENSITIVITY_SECRET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sensitivity>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sensitivity> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sensitivity>() {
            public Sensitivity findValueByNumber(int number) {
              return Sensitivity.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return logger.Options.getDescriptor().getEnumTypes().get(0);
    }

    private static final Sensitivity[] VALUES = values();

    public static Sensitivity valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sensitivity(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:logger.Sensitivity)
  }

  public static final int REDACT_FORMAT_FIELD_NUMBER = 1286;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> redactFormat = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int NAME_FIELD_NUMBER = 1287;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> name = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SENSITIVITY_FIELD_NUMBER = 1288;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      logger.Options.Sensitivity> sensitivity = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        logger.Options.Sensitivity.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024logger/options.proto\022\006logger\032 google/p" +
      "rotobuf/descriptor.proto*W\n\013Sensitivity\022" +
      "\033\n\027SENSITIVITY_UNSPECIFIED\020\000\022\023\n\017SENSITIV" +
      "ITY_PII\020\001\022\026\n\022SENSITIVITY_SECRET\020\002:5\n\rred" +
      "act_format\022\035.google.protobuf.FieldOption" +
      "s\030\206\n \001(\t:,\n\004name\022\035.google.protobuf.Field" +
      "Options\030\207\n \001(\t:H\n\013sensitivity\022\035.google.p" +
      "rotobuf.FieldOptions\030\210\n \001(\0162\023.logger.Sen" +
      "sitivityBMZ*github.com/livekit/protocol/" +
      "livekit/logger\252\002\rLiveKit.Proto\352\002\016LiveKit" +
      "::Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    redactFormat.internalInit(descriptor.getExtensions().get(0));
    name.internalInit(descriptor.getExtensions().get(1));
    sensitivity.internalInit(descriptor.getExtensions().get(2));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
