
export const LANG_LOADERS: Record<string, () => Promise<any>> = {
  js:         () => import('@shikijs/langs/javascript'),
  javascript: () => import('@shikijs/langs/javascript'),
  jsx:        () => import('@shikijs/langs/jsx'),
  ts:         () => import('@shikijs/langs/typescript'),
  typescript: () => import('@shikijs/langs/typescript'),
  tsx:        () => import('@shikijs/langs/tsx'),
  json:       () => import('@shikijs/langs/json'),
  python:     () => import('@shikijs/langs/python'),
  py:         () => import('@shikijs/langs/python'),
  rust:       () => import('@shikijs/langs/rust'),
  go:         () => import('@shikijs/langs/go'),
  java:       () => import('@shikijs/langs/java'),
  kotlin:     () => import('@shikijs/langs/kotlin'),
  swift:      () => import('@shikijs/langs/swift'),
  bash:       () => import('@shikijs/langs/bash'),
  shell:      () => import('@shikijs/langs/shellscript'),
  sh:         () => import('@shikijs/langs/shellscript'),
  sql:        () => import('@shikijs/langs/sql'),
  html:       () => import('@shikijs/langs/html'),
  css:        () => import('@shikijs/langs/css'),
  scss:       () => import('@shikijs/langs/scss'),
  yaml:       () => import('@shikijs/langs/yaml'),
  yml:        () => import('@shikijs/langs/yaml'),
  toml:       () => import('@shikijs/langs/toml'),
  xml:        () => import('@shikijs/langs/xml'),
  md:         () => import('@shikijs/langs/markdown'),
  markdown:   () => import('@shikijs/langs/markdown'),
  php:        () => import('@shikijs/langs/php'),
  ruby:       () => import('@shikijs/langs/ruby'),
  c:          () => import('@shikijs/langs/c'),
  cpp:        () => import('@shikijs/langs/cpp'),
  csharp:     () => import('@shikijs/langs/csharp'),
  cs:         () => import('@shikijs/langs/csharp'),
  dockerfile: () => import('@shikijs/langs/docker'),
  diff:       () => import('@shikijs/langs/diff'),
  graphql:    () => import('@shikijs/langs/graphql'),
  vue:        () => import('@shikijs/langs/vue'),
  svelte:     () => import('@shikijs/langs/svelte'),
}

export function isSupportedLang(lang: string): boolean {
  return lang.toLowerCase() in LANG_LOADERS
}
